// Code generated by MockGen. DO NOT EDIT.
// Source: help_done.go
//
// Generated by this command:
//
//	mockgen -source=help_done.go -destination=mocks/help_done.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tview "github.com/rivo/tview"
	gomock "go.uber.org/mock/gomock"
)

// MockApplication is a mock of Application interface.
type MockApplication struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationMockRecorder
}

// MockApplicationMockRecorder is the mock recorder for MockApplication.
type MockApplicationMockRecorder struct {
	mock *MockApplication
}

// NewMockApplication creates a new mock instance.
func NewMockApplication(ctrl *gomock.Controller) *MockApplication {
	mock := &MockApplication{ctrl: ctrl}
	mock.recorder = &MockApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplication) EXPECT() *MockApplicationMockRecorder {
	return m.recorder
}

// SetFocus mocks base method.
func (m *MockApplication) SetFocus(p tview.Primitive) *tview.Application {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFocus", p)
	ret0, _ := ret[0].(*tview.Application)
	return ret0
}

// SetFocus indicates an expected call of SetFocus.
func (mr *MockApplicationMockRecorder) SetFocus(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocus", reflect.TypeOf((*MockApplication)(nil).SetFocus), p)
}

// SetRoot mocks base method.
func (m *MockApplication) SetRoot(root tview.Primitive, fullscreen bool) *tview.Application {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoot", root, fullscreen)
	ret0, _ := ret[0].(*tview.Application)
	return ret0
}

// SetRoot indicates an expected call of SetRoot.
func (mr *MockApplicationMockRecorder) SetRoot(root, fullscreen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoot", reflect.TypeOf((*MockApplication)(nil).SetRoot), root, fullscreen)
}
